/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-08-08 01:18:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardContentView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/dev/project_goit/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Goit/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685531546529L));
    _jspx_dependants.put("jar:file:/C:/dev/project_goit/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Goit/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>나도 고양이 있어</title>\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("		@font-face {\r\n");
      out.write("		    font-family: 'Dovemayo_gothic';\r\n");
      out.write("		    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.1/Dovemayo_gothic.woff2') format('woff2');\r\n");
      out.write("		    font-weight: normal;\r\n");
      out.write("		    font-style: normal;\r\n");
      out.write("		}\r\n");
      out.write("		body,button,pre {\r\n");
      out.write("			font-family: 'Dovemayo_gothic';\r\n");
      out.write("		}\r\n");
      out.write("		#main1{\r\n");
      out.write("			border: 5px solid lightblue;\r\n");
      out.write("			border-radius: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		#Cmtsubmit{\r\n");
      out.write("			border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            width: 85x;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            font-size: 0.5em;\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            color: rgb(34, 34, 34);\r\n");
      out.write("           }\r\n");
      out.write("		#Cmtsubmit:hover{\r\n");
      out.write("            background-color: rgb(211, 253, 255);\r\n");
      out.write("        }\r\n");
      out.write("        .headBtnDiv{\r\n");
      out.write("        	margin-bottom: 30px; margin-top: 10px;\r\n");
      out.write("			margin-left: 20px; margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .headBtn{\r\n");
      out.write("        	border: 0.5px;\r\n");
      out.write("        	width: 90px;\r\n");
      out.write("        	height: 30px;\r\n");
      out.write("        	color: rgb(34, 34, 34);\r\n");
      out.write("        	border-radius: 5px;\r\n");
      out.write("        	font-size: medium;\r\n");
      out.write("        	font-weight: bold;\r\n");
      out.write("        	margin-top: 5px; margin-left: 5px; margin-right: 5px; margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .headBtn:hover{\r\n");
      out.write("        	background-color: rgb(211, 253, 255);\r\n");
      out.write("        	box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .headId{\r\n");
      out.write("        	font-size: medium;\r\n");
      out.write("        	font-weight: bold;\r\n");
      out.write("        	margin-top: 8px; margin-left: 5px; margin-right: 5px; margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .mainTable{\r\n");
      out.write("			margin-left: 25px; margin-right: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        #listBtn,#editBtn,#deleteBtn{\r\n");
      out.write("        	border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            width: 90x;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            font-size: 0.8em;\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            color: rgb(34, 34, 34);\r\n");
      out.write("            margin-left: 20px; margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        #listBtn:hover{\r\n");
      out.write("            background-color: rgb(211, 253, 255);\r\n");
      out.write("            box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        #editBtn:hover{\r\n");
      out.write("            background-color: rgb(211, 253, 255);\r\n");
      out.write("            box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        #deleteBtn:hover{\r\n");
      out.write("            background-color: rgb(211, 253, 255);\r\n");
      out.write("            box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        #cmtAll{\r\n");
      out.write("        	border-radius: 10px;\r\n");
      out.write("            background-color: rgb(233, 233, 233);\r\n");
      out.write("			padding: 20px;\r\n");
      out.write("			margin-bottom: 20px; margin-left: 20px; margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .writerDiv{margin-left: 13px; margin-right: 13px;}\r\n");
      out.write("        .writer{\r\n");
      out.write("            font-size: 0.7em; \r\n");
      out.write("            padding: 2px; padding-left: 4px; padding-right: 4px; \r\n");
      out.write("            border: none; background-color: rgb(211, 253, 255); border-radius: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .cmt{margin-left: 20px; margin-right: 13px; font-size: 1em; margin-bottom: 10px;}\r\n");
      out.write("        .eBtn,.dBtn,.cmtEditBtn{\r\n");
      out.write("        	border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            width: 32px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            font-size: 0.7em;\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            color: rgb(34, 34, 34);\r\n");
      out.write("            background-color: rgb(222, 222, 222);\r\n");
      out.write("       	}\r\n");
      out.write("        .eBtn:hover{\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .dBtn:hover{\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .cmtEditBtn:hover{\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .cmtEditdiv{\r\n");
      out.write("            margin-left: 20px; margin-bottom: 5px;\r\n");
      out.write("            float: right; margin-right: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .xxx{\r\n");
      out.write("            border: 0.2px solid gray;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            font-size: 0.5em;\r\n");
      out.write("            font-weight: normal;\r\n");
      out.write("            color: rgb(34, 34, 34);\r\n");
      out.write("        }\r\n");
      out.write("        .xxx:hover{\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .cmtEditBtnDiv{\r\n");
      out.write("            margin-left: 20px; margin-bottom: 15px; margin-top: 3px;\r\n");
      out.write("        }\r\n");
      out.write("        .editText{\r\n");
      out.write("            border: none; border-radius: 5px; outline-color: #99d3ff;\r\n");
      out.write("        }\r\n");
      out.write("        .editTextDiv{\r\n");
      out.write("            color: black; margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        textarea{\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .cdate{\r\n");
      out.write("        	padding-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .bookMarkO,.bookMarkX{\r\n");
      out.write("        	display: none;\r\n");
      out.write("        }\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<a href=\"mainPage\">\r\n");
      out.write("			<img style=\"height: 300px;\" alt=\"오류\" src=\"resources/main/main15.png\" width=\"100%\">\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"headBtnDiv\">\r\n");
      out.write("		<button type=\"button\" class=\"headBtn\" style=\"float: left;\" onclick=\"location.href='boardList'\">게시판</button>\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"main1\">\r\n");
      out.write("		<div id=\"main2\">\r\n");
      out.write("			<div><!-- 본문 -->\r\n");
      out.write("		        <table class=\"mainTable\">\r\n");
      out.write("		            <tr>\r\n");
      out.write("		                <td>\r\n");
      out.write("		                    <h3>\r\n");
      out.write("		                    	");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("	                    		");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	                    	</h3>\r\n");
      out.write("		                </td>\r\n");
      out.write("		            </tr>\r\n");
      out.write("		            <tr>\r\n");
      out.write("		                <td>\r\n");
      out.write("		                	<div style=\"margin-bottom: 20px; font-size: small;\">\r\n");
      out.write("			                	 &nbsp;<span id=\"contentId\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> · &nbsp; \r\n");
      out.write("			                	<span style=\"color: gray;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> · &nbsp;\r\n");
      out.write("			                	<span style=\"color: gray;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_hit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("		                	</div>\r\n");
      out.write("	                	</td>\r\n");
      out.write("		            </tr>\r\n");
      out.write("		            <tr>\r\n");
      out.write("		                <td>\r\n");
      out.write("		                	<div>\r\n");
      out.write("		                		 &nbsp;<img alt=\"오류\" src=\"/Goit/resources");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width: 60%\">\r\n");
      out.write("		                    </div>\r\n");
      out.write("<!-- 		                    <div style=\"margin-bottom: 10px; margin-top: 5px; white-space: pre-wrap;\"> -->\r\n");
      out.write("		                    <div style=\"white-space: pre-wrap;\">\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("		                    </div>\r\n");
      out.write("		                </td>\r\n");
      out.write("		            </tr>\r\n");
      out.write("		        </table>\r\n");
      out.write("		        <div style=\"margin: 15px;\"><!-- 리스트, 수정, 삭제 -->\r\n");
      out.write("		            <span>\r\n");
      out.write("		                <button type=\"button\" id=\"listBtn\" onclick=\"location.href='boardList'\">List</button>\r\n");
      out.write("		            </span>\r\n");
      out.write("<!-- 		                <button type=\"button\" id=\"check\">check</button> -->\r\n");
      out.write("		            \r\n");
      out.write("		            <!-- 세션 아이디, 글쓴아이디 일치시 수정, 삭제 버튼 생성 -->\r\n");
      out.write("		            ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		        </div><!-- 리스트, 수정, 삭제 -->\r\n");
      out.write("			</div><!-- 본문 -->\r\n");
      out.write("<!-- 		댓글목록 -->\r\n");
      out.write("			<div id=\"cmtAll\">\r\n");
      out.write("			<table id=\"commentList\">\r\n");
      out.write("			</table>\r\n");
      out.write("<!-- 		댓글목록 -->\r\n");
      out.write("<!-- 		댓글 작성(로그인시 보임) -->\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("<!-- 		댓글 작성 -->\r\n");
      out.write("		</div><!-- main1 -->\r\n");
      out.write("	</div><!-- main2 -->\r\n");
      out.write("	\r\n");
      out.write("		<input type=\"hidden\" name=\"id\" id=\"iid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	<form method=\"post\" action=\"boardEditPage\" id=\"contentEditForm\">\r\n");
      out.write("		<input type=\"hidden\" name=\"pageNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">			\r\n");
      out.write("		<input type=\"hidden\" name=\"amount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">			\r\n");
      out.write("		<input type=\"hidden\" name=\"b_no\" id=\"pageBno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageMaker.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("		<input type=\"hidden\" name=\"id\" id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<input type=\"hidden\" name=\"b_title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> \r\n");
      out.write("		<input type=\"hidden\" name=\"b_img\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<input type=\"hidden\" name=\"b_thumb\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_thumb}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<input type=\"hidden\" name=\"b_content\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> \r\n");
      out.write("	</form>\r\n");
      out.write("	<form method=\"post\" action=\"boardDelete\" id=\"contentDeleteForm\">\r\n");
      out.write("		<input type=\"hidden\" name=\"b_no\" id=\"b_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<input type=\"hidden\" name=\"id\" id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<!-- 	날짜 출력 하려고 사용 -->\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(\"#check\").on(\"click\", function() {\r\n");
      out.write("			var contentId = $(\"#id\").val();\r\n");
      out.write("			var id = $(\"#iid\").val();\r\n");
      out.write("			var bno = $(\"#b_no\").val();\r\n");
      out.write("			var pageBno = $(\"#pageBno\").val();\r\n");
      out.write("			var contBno = $(\"#contBno\").val();\r\n");
      out.write("			console.log(\"게시글 id ==>\"+contentId);\r\n");
      out.write("			console.log(\"dto id ==>\"+id);\r\n");
      out.write("			console.log(\"글번호 ==>\"+bno);\r\n");
      out.write("			console.log(\"페이지 글번호 ==>\"+pageBno);\r\n");
      out.write("			console.log(\"내용 글번호 ==>\"+contBno);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("// 		게시글 수정\r\n");
      out.write("		$(\"#editBtn\").on(\"click\", function() {\r\n");
      out.write("			var id = $(\"#id\").val();\r\n");
      out.write("			console.log(\"아이디값 ==>\"+id);\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"EDloginCheck\",\r\n");
      out.write("				type: \"POST\",\r\n");
      out.write("				data: { id : id },\r\n");
      out.write("				dataType: \"json\",\r\n");
      out.write("				success: function(result) {\r\n");
      out.write("					console.log(\"result값 == > \"+result);\r\n");
      out.write("//			    	로그인 아이디 일치시 수정 화면으로 이동\r\n");
      out.write("					if (result == 2) {\r\n");
      out.write("						document.getElementById(\"contentEditForm\").submit();\r\n");
      out.write("// 					아이디가 일치하지 않는 경우\r\n");
      out.write("				    } else if (result == 1) {\r\n");
      out.write("				    	alert(\"작성자가 아니라 수정할 수 없습니다.\");\r\n");
      out.write("				    	location.href = \"boardList\";\r\n");
      out.write("// 					로그인이 되어 있지 않은 경우, 로그인 페이지로 이동\r\n");
      out.write("				    } else if (result == 3){\r\n");
      out.write("				    	alert(\"로그인 정보가 없습니다.\");\r\n");
      out.write("				    	location.href = \"signInPage\";\r\n");
      out.write("				  	}\r\n");
      out.write("				},\r\n");
      out.write("				error: function () {\r\n");
      out.write("					alert(\"오류\");\r\n");
      out.write("	            }\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("// 		게시글 삭제\r\n");
      out.write("		$(\"#deleteBtn\").on(\"click\", function() {\r\n");
      out.write("			var id = $(\"#id\").val();\r\n");
      out.write("			console.log(\"아이디값 ==>\"+id);\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"EDloginCheck\",\r\n");
      out.write("				type: \"POST\",\r\n");
      out.write("				data: { id : id },\r\n");
      out.write("				dataType: \"json\",\r\n");
      out.write("				success: function(result) {\r\n");
      out.write("					console.log(\"result값 == > \"+result);\r\n");
      out.write("//			    	로그인 아이디 일치시 삭제\r\n");
      out.write("					if (result == 2) {\r\n");
      out.write("						if(confirm(\"게시글을 삭제를 하시겠습니까?\")){\r\n");
      out.write("							document.getElementById(\"contentDeleteForm\").submit();\r\n");
      out.write("							alert(\"정상적으로 삭제되었습니다.\");\r\n");
      out.write("						}else{\r\n");
      out.write("						}\r\n");
      out.write("// 					아이디가 일치하지 않는 경우\r\n");
      out.write("				    } else if (result == 1) {\r\n");
      out.write("				    	alert(\"작성자가 아니라 삭제할 수 없습니다.\");\r\n");
      out.write("				    	location.href = \"boardList\";\r\n");
      out.write("// 					로그인이 되어 있지 않은 경우, 로그인 페이지로 이동\r\n");
      out.write("				    } else if (result == 3){\r\n");
      out.write("				    	alert(\"로그인 정보가 없습니다.\");\r\n");
      out.write("				    	location.href = \"signInPage\";\r\n");
      out.write("				  	}\r\n");
      out.write("				},\r\n");
      out.write("				error: function () {\r\n");
      out.write("					alert(\"오류\");\r\n");
      out.write("	            }\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("// 		댓글 작성\r\n");
      out.write("		$(\"#Cmtsubmit\").on(\"click\", function() {\r\n");
      out.write("			var formData = $(\"#CmtWriteForm\").serialize();\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"boardCmtWrite\",\r\n");
      out.write("				type: \"POST\",\r\n");
      out.write("				data: formData,\r\n");
      out.write("// 				dataType: \"json\",\r\n");
      out.write("				success: function(result) {\r\n");
      out.write("					console.log(\"result값 == > \"+result);\r\n");
      out.write("					if (result == \"2\") {\r\n");
      out.write("				    	$(\"#texta\").val(\"\");\r\n");
      out.write("				    	getComments();\r\n");
      out.write("				    	alert(\"댓글 작성이 완료 되었습니다.\");\r\n");
      out.write("				    }\r\n");
      out.write("				},\r\n");
      out.write("				error: function () {\r\n");
      out.write("					alert(\"오류\");\r\n");
      out.write("	            }\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("// 		댓글목록 불러오기\r\n");
      out.write("		function getComments() {\r\n");
      out.write("			var b_no = $(\"#b_no\").val();\r\n");
      out.write("			console.log(\"댓글 목록 불러오기 b_no값 == > \"+b_no);\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            type: \"GET\",\r\n");
      out.write("	            url: \"boardCmtList\",\r\n");
      out.write("	            data: { b_no: b_no },\r\n");
      out.write("	            dataType: \"json\",\r\n");
      out.write("	            success: function (commentList) {\r\n");
      out.write("	                // 댓글 목록을 가공하여 commentList 영역에 추가\r\n");
      out.write("	                var cmtList = $(\"#commentList\");\r\n");
      out.write("	                cmtList.empty();\r\n");
      out.write("	                $.each(commentList, function (index, comment) {\r\n");
      out.write("	                var c_date = moment(comment.c_date).format('YYYY-MM-DD');\r\n");
      out.write("	                    var html =				'<tr>'\r\n");
      out.write("                    		+	'<td colspan=\"2\">' \r\n");
      out.write("                    		+		'<form action=\"boardCmtDelete\" method=\"post\" class=\"cmtDelete\">'\r\n");
      out.write("                   			+			'<input type=\"hidden\" name=\"c_no\" value=\"' + parseInt(comment.c_no) + '\">' \r\n");
      out.write("                    		+			'<input type=\"hidden\" name=\"id\" value=\"' + comment.id + '\">' \r\n");
      out.write("                    		+		'</form>' \r\n");
      out.write("                    		+		'<div class=\"writerDiv\">' \r\n");
      out.write("                    		+			'<span><b>' + comment.id + '</b></span>';\r\n");
      out.write("                    		\r\n");
      out.write("                    		if ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == comment.id) {\r\n");
      out.write("                    		    html += '&nbsp;<span class=\"writer\">작성자</span>';\r\n");
      out.write("                    		}\r\n");
      out.write("                    		html +=			'&nbsp;&nbsp;<span class=\"cdate\">' + c_date + '</span>&nbsp;'; \r\n");
      out.write("                    		\r\n");
      out.write("                    		if (comment.id == '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("') {\r\n");
      out.write("                    		    html +=	'<span style=\"float: right;\">'\r\n");
      out.write("                    		    	+	'<button type=\"button\" class=\"eBtn\">수정</button>&nbsp;'\r\n");
      out.write("                    		    	+	'<button type=\"button\" class=\"dBtn\">삭제</button>'\r\n");
      out.write("                    		    	+ '</span>';\r\n");
      out.write("                    		}\r\n");
      out.write("                    		html +=		'</div>' \r\n");
      out.write("                    		+	'</td>' \r\n");
      out.write("                    		+'</tr>' \r\n");
      out.write("                    		+'<tr>' \r\n");
      out.write("                    		+	'<td colspan=\"2\">' \r\n");
      out.write("                    		+		'<div class=\"cmt\" style=\"white-space: pre-wrap;\">' + comment.c_content + '</div>' \r\n");
      out.write("                    		+	'</td>' \r\n");
      out.write("                    		+'</tr>' \r\n");
      out.write("                    		+'<tr>' \r\n");
      out.write("                    		+	'<td colspan=\"2\" class=\"editShow\" style=\"display: none;\">' \r\n");
      out.write("                    		+'<form method=\"post\" action=\"boardCmtEdit\" class=\"cmtEdit\">' \r\n");
      out.write("                    		+		'<div class=\"cmtEditdiv\">' \r\n");
      out.write("                    		+			'<button type=\"button\" class=\"xxx\">x</button>' \r\n");
      out.write("                    		+		'</div>' \r\n");
      out.write("                    		+		'<div class=\"editTextDiv\">' \r\n");
      out.write("                    		+			'<textarea rows=\"5\" cols=\"68\" name=\"c_content\" size=\"300\" class=\"editText\">' + comment.c_content + '</textarea>' \r\n");
      out.write("                    		+			'<input type=\"hidden\" name=\"c_no\" value=\"' + parseInt(comment.c_no) + '\">' \r\n");
      out.write("                    		+			'<input type=\"hidden\" name=\"id\" value=\"' + comment.id + '\">' \r\n");
      out.write("                    		+		'</div>' \r\n");
      out.write("                    		+		'<div class=\"cmtEditBtnDiv\">' \r\n");
      out.write("                    		+			'<button type=\"button\" class=\"cmtEditBtn\">수정</button>'\r\n");
      out.write("                    		+		'</div>' \r\n");
      out.write("                    		+	'</form>' \r\n");
      out.write("                    		+	'</td>' \r\n");
      out.write("                    		+'</tr>';\r\n");
      out.write("	                	cmtList.append(html);\r\n");
      out.write("	                });\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function (xhr, status, error) {\r\n");
      out.write("	                console.error(error);\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write(" 		}\r\n");
      out.write("\r\n");
      out.write("//		댓글 목록을 불러오도록 호출\r\n");
      out.write("    	$(document).ready(function () {\r\n");
      out.write("//     		댓글을 가져올 게시물 번호\r\n");
      out.write("        	var b_no = $(\"#b_no\").val();\r\n");
      out.write("        	console.log(\"ㅈㅔ말이 들리시나요?ㅋ b_no값 == > \"+b_no);\r\n");
      out.write("        	getComments();\r\n");
      out.write("    	});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("// 		댓글 수정 열고 닫기\r\n");
      out.write("		$(document).ready(function () {\r\n");
      out.write("// 			$(\".eBtn\").on(\"click\", function() {\r\n");
      out.write("			$(document).on(\"click\", \".eBtn\", function() {\r\n");
      out.write("	//			누른곳의 tr값 다음 다음 tr 값\r\n");
      out.write("				console.log(\"수정버튼 눌러짐?\");\r\n");
      out.write("				var editRow = $(this).closest(\"tr\").next(\"tr\").next(\"tr\").find(\".editShow\");\r\n");
      out.write("				editRow.show();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(document).ready(function () {\r\n");
      out.write("			$(document).on(\"click\", \".xxx\", function() {\r\n");
      out.write("// 			$(\".xxx\").on(\"click\", function() {\r\n");
      out.write("			var editRow = $(this).closest(\"tr\").find(\".editShow\");\r\n");
      out.write("			editRow.hide();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("// 		댓글 수정\r\n");
      out.write("		$(document).ready(function () {\r\n");
      out.write("			$(document).on(\"click\", \".cmtEditBtn\",function() {\r\n");
      out.write("				console.log(\"댓글수정이요 제발\");				\r\n");
      out.write("				var formData = $(this).closest(\"tr\").find(\".cmtEdit\").serialize();\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"boardCmtEdit\",\r\n");
      out.write("					type: \"POST\",\r\n");
      out.write("					data: formData,\r\n");
      out.write("					success: function(result) {\r\n");
      out.write("						console.log(\"result값 == > \"+result);\r\n");
      out.write("						if (result == \"2\") {\r\n");
      out.write("					    	getComments();\r\n");
      out.write("					    	alert(\"댓글 수정이 완료 되었습니다.\");\r\n");
      out.write("					    }\r\n");
      out.write("					},\r\n");
      out.write("					error: function () {\r\n");
      out.write("						alert(\"오류\");\r\n");
      out.write("		            }\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("// 		댓글 삭제\r\n");
      out.write("		$(document).ready(function () {\r\n");
      out.write("			$(document).on(\"click\", \".dBtn\", function() {\r\n");
      out.write("				var formData = $(this).closest(\"tr\").find(\".cmtDelete\").serialize();\r\n");
      out.write("				if (confirm(\"정말 삭제 하시겠습니까?\")) {\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url: \"boardCmtDelete\",\r\n");
      out.write("						type: \"POST\",\r\n");
      out.write("						data: formData,\r\n");
      out.write("						success: function(result) {\r\n");
      out.write("							console.log(\"result값 == > \"+result);\r\n");
      out.write("							if (result == \"2\") {\r\n");
      out.write("						    	getComments();\r\n");
      out.write("						    	alert(\"댓글이 삭제 되었습니다.\");\r\n");
      out.write("						    }\r\n");
      out.write("						},\r\n");
      out.write("						error: function () {\r\n");
      out.write("							alert(\"오류\");\r\n");
      out.write("			            }\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("// 		북마크 여부 불러오기\r\n");
      out.write("		function getBookmark() {\r\n");
      out.write("			var b_no = $(\"#b_no\").val();\r\n");
      out.write("			var id = $(\"#iid\").val();\r\n");
      out.write("			console.log(\"북마크 불러오기 b_no값 == > \"+b_no);\r\n");
      out.write("			console.log(\"북마크 불러오기 id값 == > \"+id);\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            type: \"GET\",\r\n");
      out.write("	            url: \"bookMarkCheck\",\r\n");
      out.write("	            data: { b_no: b_no,\r\n");
      out.write("	            		id : id},\r\n");
      out.write("	            dataType: \"json\",\r\n");
      out.write("	            success: function (favDto) {\r\n");
      out.write("// 					alert(\"favDto ==>\"+favDto)            	\r\n");
      out.write("					if (favDto == 2) {\r\n");
      out.write("						$(\".bookMarkO\").show();\r\n");
      out.write("						$(\".bookMarkX\").hide();\r\n");
      out.write("					}else{\r\n");
      out.write("						$(\".bookMarkX\").show();\r\n");
      out.write("						$(\".bookMarkO\").hide();\r\n");
      out.write("					}\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function (xhr, status, error) {\r\n");
      out.write("	                console.error(error);\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write(" 		}\r\n");
      out.write("		\r\n");
      out.write("//		북마크 여부를 불러오도록 호출\r\n");
      out.write("    	$(document).ready(function () {\r\n");
      out.write("//     		북마크 여부 확인할 게시물 번호\r\n");
      out.write("        	var b_no = $(\"#b_no\").val();\r\n");
      out.write("        	getBookmark();\r\n");
      out.write("    	});\r\n");
      out.write("    	\r\n");
      out.write("// 		북마크O 클릭시 삭제\r\n");
      out.write("// 		북마크X 클릭시 추가\r\n");
      out.write("		$(\".favX\").on(\"click\", function() {\r\n");
      out.write("			var b_no = $(\"#b_no\").val();\r\n");
      out.write("			var id = $(\"#iid\").val();\r\n");
      out.write("			console.log(\"북마크 b_no값 == > \"+b_no);\r\n");
      out.write("			console.log(\"북마크 id값 == > \"+id);\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"bookMark\",\r\n");
      out.write("				type: \"POST\",\r\n");
      out.write("				data: { b_no: b_no,\r\n");
      out.write("            			id : id},\r\n");
      out.write("				dataType: \"json\",\r\n");
      out.write("				success: function(result) {\r\n");
      out.write("					console.log(\"result값 == > \"+result);\r\n");
      out.write("					if (result == \"2\") {\r\n");
      out.write("				    	getBookmark();\r\n");
      out.write("				    }\r\n");
      out.write("				},\r\n");
      out.write("				error: function () {\r\n");
      out.write("					alert(\"오류\");\r\n");
      out.write("	            }\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("// 		북마크O 클릭시 삭제\r\n");
      out.write("		$(\".favO\").on(\"click\", function() {\r\n");
      out.write("			var b_no = $(\"#b_no\").val();\r\n");
      out.write("			var id = $(\"#iid\").val();\r\n");
      out.write("			console.log(\"북마크 b_no값 == > \"+b_no);\r\n");
      out.write("			console.log(\"북마크 id값 == > \"+id);\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"bookMarkDelete\",\r\n");
      out.write("				type: \"POST\",\r\n");
      out.write("				data: { b_no: b_no,\r\n");
      out.write("            			id : id},\r\n");
      out.write("				dataType: \"json\",\r\n");
      out.write("				success: function(result) {\r\n");
      out.write("					console.log(\"result값 == > \"+result);\r\n");
      out.write("					if (result == \"2\") {\r\n");
      out.write("				    	getBookmark();\r\n");
      out.write("				    }\r\n");
      out.write("				},\r\n");
      out.write("				error: function () {\r\n");
      out.write("					alert(\"오류\");\r\n");
      out.write("	            }\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	<footer style=\"font-size: 0.1em; color: lightgray;\">\r\n");
      out.write("		<a href=\"https://kr.freepik.com/free-vector/blue-pastel-background-grid-pattern-cute-design-vector_20346221.htm#query=%EA%B7%80%EC%97%AC%EC%9A%B4%20%ED%8C%A8%ED%84%B4&position=6&from_view=keyword&track=ais\">작가 rawpixel.com</a> 출처 Freepik\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/boardContentView.jsp(164,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<button type=\"button\" class=\"headBtn\" style=\"float: right;\" onclick=\"location.href='signUpPage'\">회원가입</button>&nbsp;\r\n");
          out.write("			<button type=\"button\" class=\"headBtn\" style=\"float: right;\" onclick=\"location.href='signInPage'\">로그인</button>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/boardContentView.jsp(168,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<button type=\"button\" class=\"headBtn\" style=\"float: right;\" onclick=\"location.href='signOut'\">로그아웃</button>&nbsp;\r\n");
          out.write("			<button type=\"button\" class=\"headBtn\" style=\"float: right;\" onclick=\"location.href='myPage'\">마이페이지</button>\r\n");
          out.write("			<span class=\"headId\" style=\"float: right;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/boardContentView.jsp(182,23) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				                    <span class=\"bookMarkO\">\r\n");
          out.write("				                    	<a href=\"#\" class=\"favO\">\r\n");
          out.write("				                    		<img alt=\"오류\" src=\"resources/main/bookMarkO.png\" style=\"width: 35px;\">\r\n");
          out.write("			                    		</a>\r\n");
          out.write("		                    		</span>\r\n");
          out.write("				                    <span class=\"bookMarkX\">\r\n");
          out.write("				                    	<a href=\"#\" class=\"favX\">\r\n");
          out.write("				                    		<img alt=\"오류\" src=\"resources/main/bookMarkX.png\" style=\"width: 35px;\">\r\n");
          out.write("				                    	</a>\r\n");
          out.write("			                    	</span>\r\n");
          out.write("			                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/boardContentView.jsp(225,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.id eq dto.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		            	<span style=\"float: right;\">\r\n");
          out.write("			                <button type=\"button\" id=\"editBtn\">Edit</button>\r\n");
          out.write("			                <button type=\"button\" id=\"deleteBtn\">Delete</button>\r\n");
          out.write("		                </span>\r\n");
          out.write("		            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/boardContentView.jsp(239,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<form method=\"post\" id=\"CmtWriteForm\">\r\n");
          out.write("					<table style=\"margin-top: 20px; width: 550px;\">\r\n");
          out.write("						<tr>\r\n");
          out.write("							<td colspan=\"2\" style=\"background-color: white;\">\r\n");
          out.write("								<input type=\"hidden\" name=\"b_no\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ContentView.b_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<div style=\"background-color: white; padding: 7px;\">\r\n");
          out.write("									<div>\r\n");
          out.write("										<textarea id=\"texta\" rows=\"5\" cols=\"80\" name=\"c_content\" size=\"300\" style=\"border: none; border-radius: 5px; outline-color: #99d3ff\" placeholder=\"댓글을 작성해 주세요.\"></textarea>		\r\n");
          out.write("									</div>\r\n");
          out.write("									<div style=\"float: right; margin-right: 15px; margin-top: 5px; margin-bottom: 7px;\">\r\n");
          out.write("										<button type=\"button\" id=\"Cmtsubmit\" style=\"font-size: small;\">댓글등록</button>\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("							</td>\r\n");
          out.write("						</tr>\r\n");
          out.write("					</table>\r\n");
          out.write("				</form>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
