/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-08-06 17:42:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUpPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685531546529L));
    _jspx_dependants.put("jar:file:/C:/dev/project_goit/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Goit/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>나도 고양이 있어</title>\r\n");
      out.write("    <style>\r\n");
      out.write("    	@font-face {\r\n");
      out.write("		    font-family: 'Dovemayo_gothic';\r\n");
      out.write("		    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.1/Dovemayo_gothic.woff2') format('woff2');\r\n");
      out.write("		    font-weight: normal;\r\n");
      out.write("		    font-style: normal;\r\n");
      out.write("		}\r\n");
      out.write("		body,button,textarea {\r\n");
      out.write("			font-family: 'Dovemayo_gothic';\r\n");
      out.write("		}\r\n");
      out.write("		#main1{\r\n");
      out.write("			border: 5px solid lightblue;\r\n");
      out.write("			border-radius: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		.headBtnDiv{\r\n");
      out.write("			margin-bottom: 30px; margin-top: 10px;\r\n");
      out.write("			margin-left: 20px; margin-right: 20px;\r\n");
      out.write("		}\r\n");
      out.write("    	.headBtn{\r\n");
      out.write("        	border: 0.5px;\r\n");
      out.write("        	width: 90px;\r\n");
      out.write("        	height: 30px;\r\n");
      out.write("        	color: rgb(34, 34, 34);\r\n");
      out.write("        	border-radius: 5px;\r\n");
      out.write("        	font-size: medium;\r\n");
      out.write("        	font-weight: bold;\r\n");
      out.write("        	margin: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .headBtn:hover{\r\n");
      out.write("        	background-color: rgb(211, 253, 255);\r\n");
      out.write("        	box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .headId{\r\n");
      out.write("        	font-size: medium;\r\n");
      out.write("        	font-weight: bold;\r\n");
      out.write("        	margin-top: 8px; margin-left: 5px; margin-right: 5px; margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        table{\r\n");
      out.write("            margin-left: auto; margin-right: auto;\r\n");
      out.write("            margin-top: 40px; margin-bottom: 40px;\r\n");
      out.write("            border: 0.2px solid gray;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            align-content: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-collapse: separate;\r\n");
      out.write("			border-spacing: 0 0 0 20px;\r\n");
      out.write("        }\r\n");
      out.write("        tr{\r\n");
      out.write("        	margin: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        input{\r\n");
      out.write("            border: 0.5px solid gray;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            height: 23px;\r\n");
      out.write("            font-family: 'Dovemayo_gothic';\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .write:focus{\r\n");
      out.write("            background-color: #E8F5FF;\r\n");
      out.write("            color: rgb(75, 75, 75);\r\n");
      out.write("            outline: 2px solid gray;\r\n");
      out.write("        }\r\n");
      out.write("        #signUp{\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            font-size: medium;\r\n");
      out.write("        }\r\n");
      out.write("        #signUp:hover{\r\n");
      out.write("            background-color: #E8F5FF;\r\n");
      out.write("            box-shadow: 1px 1px 5px #ccc;\r\n");
      out.write("        }\r\n");
      out.write("        .displaynone{\r\n");
      out.write("        	color: red;\r\n");
      out.write("        	font-size: small;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 상단 -->\r\n");
      out.write("	<div>\r\n");
      out.write("		<a href=\"mainPage\">\r\n");
      out.write("			<img style=\"height: 300px;\" alt=\"오류\" src=\"resources/main/main15.png\" width=\"100%\">\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"headBtnDiv\">\r\n");
      out.write("		<button type=\"button\" class=\"headBtn\" style=\"float: left;\" onclick=\"location.href='boardList'\">게시판</button>\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- 상단 -->\r\n");
      out.write("	<div id=\"main1\">\r\n");
      out.write("		<div id=\"main2\">\r\n");
      out.write("			<div><!-- 본문 -->\r\n");
      out.write("				<form method=\"post\" action=\"signUp\" name=\"signup\">\r\n");
      out.write("					<table>\r\n");
      out.write("						<caption><h2>회원가입</h2></caption>\r\n");
      out.write("						<tr>\r\n");
      out.write("			                <td>아이디</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("			                <td style=\"color: gray; font-size: small;\">\r\n");
      out.write("			                	영어,숫자,_,-만 사용 가능하고 5~10자\r\n");
      out.write("			                </td>\r\n");
      out.write("						</tr>\r\n");
      out.write("			            <tr>\r\n");
      out.write("			                <td>\r\n");
      out.write("			                    <!-- <input type=\"text\" name=\"id\" id=\"id\" placeholder=\"아이디를 입력하세요\"> -->\r\n");
      out.write("			                    <input type=\"text\" name=\"id\" id=\"id\" class=\"write\" size=\"60\" maxlength=\"10\">\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("						<tr id=\"idX\" style=\"display: none;\">\r\n");
      out.write("							<td style=\"height: 10px;\">\r\n");
      out.write("			                   	<span class=\"displaynone\">사용할 수 없는 아이디입니다. 다른 아이디를 입력해 주세요.</span>\r\n");
      out.write("			                </td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr id=\"idO\" style=\"display: none;\">\r\n");
      out.write("			                <td>\r\n");
      out.write("			                    <span class=\"displaynone\">사용 가능한 아이디 입니다.</span>\r\n");
      out.write("			                </td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("			                <td>\r\n");
      out.write("			                	비밀번호\r\n");
      out.write("			                </td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("			                <td style=\"color: gray; font-size: small;\">\r\n");
      out.write("			                	<span>5~15자의 영문 대/소문자, 숫자, 특수문자를 사용해 주세요.</span>\r\n");
      out.write("			                </td>\r\n");
      out.write("						</tr>\r\n");
      out.write("			            <tr>\r\n");
      out.write("			                <td>\r\n");
      out.write("			                    <input type=\"password\" id=\"pwd1\" class=\"write\" size=\"60\" maxlength=\"15\">\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("			                <td>비밀번호 확인</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("			            <tr>\r\n");
      out.write("			                <td>\r\n");
      out.write("			                    <input type=\"password\" name=\"pwd\" id=\"pwd2\" class=\"write\" size=\"60\" maxlength=\"15\">\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("			            <tr id=\"pwdX\" style=\"display: none;\">\r\n");
      out.write("			                <td>\r\n");
      out.write("			                    <span class=\"displaynone\">비밀번호가 일치하지 않습니다.</span>\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("			            <tr id=\"pwdO\" style=\"display: none;\">\r\n");
      out.write("			                <td>\r\n");
      out.write("								<span class=\"displaynone\">비밀번호가 일치합니다.</span>\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("			                <td>이름</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("			                <td style=\"color: gray; font-size: small;\">\r\n");
      out.write("			                	한글 2~6자\r\n");
      out.write("			                </td>\r\n");
      out.write("						</tr>\r\n");
      out.write("			            <tr>\r\n");
      out.write("			                <td colspan=\"2\">\r\n");
      out.write("			                    <input type=\"text\" name=\"name\" id=\"name\" class=\"write\" size=\"60\" maxlength=\"6\">\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("			                <td>이메일</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("			            <tr>\r\n");
      out.write("			                <td colspan=\"2\">\r\n");
      out.write("			                    <input type=\"text\" name=\"email\" id=\"email\" class=\"write\" size=\"60\">\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("			            <tr>\r\n");
      out.write("			                <td align=\"center\">\r\n");
      out.write("			                    <div style=\"margin: 20px;\">\r\n");
      out.write("			                        <button type=\"button\" id=\"signUp\">회원가입</button>\r\n");
      out.write("			                    </div>\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div><!-- 본문 -->\r\n");
      out.write("		</div><!-- main1 -->\r\n");
      out.write("	</div><!-- main2 -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var idCheck = false;\r\n");
      out.write("        var pwdCheck = false;\r\n");
      out.write("        $(\"#id\").on(\"propertychange change keyup paste input\", function () {\r\n");
      out.write("        	var id = $(this).val();\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"idCheck\",\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                data: {id : id},\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success : function(result) {\r\n");
      out.write("                    if (result == 2) {\r\n");
      out.write("                        $(\"#idO\").show();\r\n");
      out.write("                        $(\"#idX\").hide();\r\n");
      out.write("                        idCheck = true;\r\n");
      out.write("                    }else if (result == 1) {\r\n");
      out.write("                        $(\"#idX\").show();\r\n");
      out.write("                        $(\"#idO\").hide();\r\n");
      out.write("                        idCheck;\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error: function(){\r\n");
      out.write("                    alert(\"오류\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        $(\"#pwd2\").on(\"propertychange change keyup paste input\", function () {\r\n");
      out.write("        	console.log(\"비밀번호 입력중\")\r\n");
      out.write("			if ($(\"#pwd1\").val() != $(\"#pwd2\").val()) {\r\n");
      out.write("			    $(\"#pwdX\").show();\r\n");
      out.write("			    $(\"#pwdO\").hide();\r\n");
      out.write("			}else if ($(\"#pwd1\").val() == $(\"#pwd2\").val()) {\r\n");
      out.write("			    $(\"#pwdO\").show();\r\n");
      out.write("			    $(\"#pwdX\").hide();\r\n");
      out.write("			}\r\n");
      out.write("        });\r\n");
      out.write("//      아이디, 비밀번호, 이름, 이메일 유효성검사를 위한 정규식\r\n");
      out.write("// 		영어,숫자,_,-만 사용 가능하고 5~10자\r\n");
      out.write("        var userIdCheck = RegExp(/^[A-Za-z0-9_\\-]{5,10}$/);\r\n");
      out.write("//      영문 대/소문자, 숫자, 특수문자를 하나 이상 포함하여 5~15자\r\n");
      out.write("        var userPwdCheck = (/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^*?]).{5,15}$/);\r\n");
      out.write("//         한글 2~6자\r\n");
      out.write("        var userNameCheck = RegExp(/^[가-힣]{2,6}$/);\r\n");
      out.write("       								\r\n");
      out.write("        var userEmailCheck = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/);\r\n");
      out.write("        \r\n");
      out.write("//      회원가입 버튼 눌렀을때\r\n");
      out.write("        $(\"#signUp\").on(\"click\", function() {\r\n");
      out.write("			if ($(\"#id\").val() == \"\") {\r\n");
      out.write("				alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("				$(\"#id\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if(!userIdCheck.test($(\"#id\").val())){\r\n");
      out.write("		        alert(\"아이디 형식에 맞게 입력해주세요.\");\r\n");
      out.write("		        $(\"#id\").focus();\r\n");
      out.write("		        return false;\r\n");
      out.write("	      	}\r\n");
      out.write("        	if (idCheck == false) {\r\n");
      out.write("        		alert(\"이미 존재하는 아이디 입니다.\");\r\n");
      out.write("				$(\"#id\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if ($(\"#id\").val().length < 5) {\r\n");
      out.write("				alert(\"아이디는 5글자 이상이여야 합니다\");\r\n");
      out.write("				$(\"#id\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if ($(\"#pwd1\").val() == \"\" || $(\"#pwd2\").val() == \"\") {\r\n");
      out.write("				alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("				$(\"#pwd1\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if ($(\"#id\").val() == $(\"#pwd1\").val()) {\r\n");
      out.write("				alert(\"아이디를 비밀번호로 사용할 수 없습니다.\");\r\n");
      out.write("				$(\"#pwd1\").val(\"\");\r\n");
      out.write("				$(\"#pwd1\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if ($(\"#pwd1\").val().length < 5) {\r\n");
      out.write("				alert(\"비밀번호는 5자 이상이여야 합니다.\");\r\n");
      out.write("				$(\"#pwd1\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if ($(\"#pwd1\").val() != $(\"#pwd2\").val()) {\r\n");
      out.write("				alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("				$(\"#pwd1\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if(!userPwdCheck.test($(\"#pwd1\").val())){\r\n");
      out.write("		        alert(\"비밀번호 형식에 맞게 입력해주세요.\");\r\n");
      out.write("		        $(\"#pwd1\").focus();\r\n");
      out.write("		        return false;\r\n");
      out.write("	      	}\r\n");
      out.write("			if ($(\"#name\").val() == \"\") {\r\n");
      out.write("				alert(\"이름을 입력해주세요.\");\r\n");
      out.write("				$(\"#name\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if(!userNameCheck.test($(\"#name\").val())){\r\n");
      out.write("		        alert(\"정확한 이름을 적어주세요.\");\r\n");
      out.write("		        $(\"#name\").focus();\r\n");
      out.write("		        return false;\r\n");
      out.write("	      	}\r\n");
      out.write("			if ($(\"#email\").val() == \"\") {\r\n");
      out.write("				alert(\"이메일을 입력해주세요.\");\r\n");
      out.write("				$(\"#email\").focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			if(!userEmailCheck.test($(\"#email\").val())){\r\n");
      out.write("		        alert(\"이메일주소가 올바르지 않습니다.\");\r\n");
      out.write("		        $(\"#email\").focus();\r\n");
      out.write("		        return false;\r\n");
      out.write("	      	}\r\n");
      out.write("			document.signup.submit();\r\n");
      out.write("		});\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/signUpPage.jsp(97,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<button type=\"button\" class=\"headBtn\" style=\"float: right;\" onclick=\"location.href='signUpPage'\">회원가입</button>\r\n");
          out.write("			&nbsp;<button type=\"button\" class=\"headBtn\" style=\"float: right;\" onclick=\"location.href='signInPage'\">로그인</button>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/signUpPage.jsp(101,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<button type=\"button\" class=\"headBtn\" style=\"float: right;\" onclick=\"location.href='signOut'\">로그아웃</button>&nbsp;\r\n");
          out.write("			<button type=\"button\" class=\"headBtn\" style=\"float: right;\" onclick=\"location.href='myPage'\">마이페이지</button>\r\n");
          out.write("			<span class=\"headId\" style=\"float: right;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
